#:schema node_modules/wrangler/config-schema.json
name = "hntopscraper"
main = "src/index.ts"
compatibility_date = "2024-06-20"

route = { pattern = "hn-top-tidbyt-prod.nkcmr.dev", custom_domain = true }
workers_dev = false

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "e18b4a544a094ab4bb46ad2702d0b9f3"

[version_metadata]
binding = "CF_VERSION_METADATA"
